version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  cronsql:
    build:
      context: .
    restart: always
    depends_on:
      database:
        condition: service_healthy
  harness:
    build:
      context: harness
    restart: always
    depends_on:
      database:
        condition: service_healthy
